apiVersion: v1
kind: LimitRange
metadata:
  name: limitexample
spec:
  limits:
    - type: Pod
      max:
        cpu: 1
        memory: 1Gi
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 10Mi
      default:
        cpu: 200m
        memory: 100Mi
      max:
        cpu: 1
        memory: 1Gi
